# Generated by Django 4.1.7 on 2023-03-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_reservations', '0002_reservation_is_draft_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='comments',
        ),
        migrations.AddField(
            model_name='claim',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='netbox_reservations.claim'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
