# Generated by Django 4.1.7 on 2023-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_reservations', '0003_alter_claim_managers_claim_level_claim_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='claim',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='comments',
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
