# Generated by Django 4.1.7 on 2023-03-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_reservations', '0003_remove_reservation_comments_claim_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='netbox_reservations.claim'),
        ),
    ]
