# Generated by Django 4.1.7 on 2023-03-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_reservations', '0004_alter_claim_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={},
        ),
    ]
